# pod lib lint
name: pod lib lint

on: [push, pull_request]

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  pod-lib-lint:
    runs-on: macos-14
    # https://github.com/SDWebImage/SDWebImage/blob/master/.github/workflows/CI.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Pod Update
        run: pod update --project-directory=./Example

      - name: Run Podsepec Lint
        run: |
          set -o pipefail
          pod lib lint ZDLibffi.podspec --allow-warnings --skip-tests
